### PR TITLE
chore: remove unused dependency (`source-map`)

### PR DESCRIPTION
**Pull request by diegofaria**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@diegofaria why?

**Comment by diegofaria** [comment]
it looks like its not being used by the code, or i am too newbie?! x)

**Comment by evilebottnawi** [comment]
Seems `SourceMap` never used.

/cc @d3viant0ne

**Comment by diegofaria** [comment]
I don't really know if it was needed the SourcMap depedency within tests.

Can someone check?

@d3viant0ne @michael-ciniawsky @evilebottnawi

**Comment by d3viant0ne** [comment]
@diegofaria - You need to sign the CLA before this can be merged.

**Comment by diegofaria** [comment]
I already did it @d3viant0ne :)

**Comment by michael-ciniawsky** [comment]
@zuohaocheng Do you have any idea why the `with`keyword is used in the test and if it's still needed ? Otherwise I need to ask Tobias about it :D

**Comment by zuohaocheng** [comment]
@michael-ciniawsky I'm not sure, but it looks more like a comment for me, as these are not real JavaScript file: `without` is definitely an illegal token. I would prefer to preserve them, and if possible, make it more clear to show these are _not_ files in specific language.

What is done in `source-map-loader` does not include parsing the JavaScript file, as it only uses regex to match source map directive. As my understanding, it should be able to be used with other types of file, say, css.

**Comment by diegofaria** [comment]
What do you guys think it's left here?

@zuohaocheng @michael-ciniawsky

**Comment by zuohaocheng** [comment]
@diegofaria Please kindly correct me if it's not the case. As mentioned in earlier comment, I think it would be nice to leave those `with`s as comment in test cases.

Removing unused dependency looks perfect forme.

**Comment by diegofaria** [comment]
@zuohaocheng can you check if now it's correct?

**Comment by StarpTech** [comment]
What's the status?

**Pull request closed without merging**
