### PR TITLE
fix: Handle exception on loading invalid source maps (#65)

### PR DESCRIPTION
**Pull request by fimius23**
Added a try catch that's pretty much the same as the base64 fix.

### CODE REVIEW

**Comment by fimius23** [comment]
@jsf-clabot  In writing the tests I've noticed that the logic calls addDependency() once the file can be resolved. If there's an error parsing the source map should I remove the dependency?

**Comment by fimius23** [comment]
Or I could just move the addDependency() call into the try?

**Comment by fimius23** [comment]
I figured that since the dependency isn't removed if there's an error reading the file, then I don't need to worry about it.

**Comment by michael-ciniawsky** [comment]
Released in [`v0.2.4`](https://github.com/webpack-contrib/source-map-loader/releases/tag/v0.2.4) 🎉

**Pull request merged**
