### PR TITLE
Elaborate on plugin usage and benefits.

### PR DESCRIPTION
**Pull request by ecarlisle**

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
Closes #32

**Comment by michael-ciniawsky** [comment]
@ecarlisle You need to sign the CLA, but there seems to be an error with your email :) 

cc @d3viant0ne

**Comment by ecarlisle** [comment]
That's very strange about the e-mail address.  I just signed the CLA so hopefully that will process.

**Comment by michael-ciniawsky** [comment]
@ecarlisle Are the email adresses in `git config` and your github profile the same ? If not you need to align them close and reopen the PR to trigger the bot again 😛 . Optimal would be using the one the bot already accepted. Currently the bot thinks, there are two contribs to this PR, because of the eventual address mismatch

> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our Contributor License Agreement before we can accept your contribution.
1 out of 2 committers have signed the CLA.

✅ ecarlisle // <= 
❌ Eric Carlisle

**Comment by ecarlisle** [comment]
I discovered why the e-mail address was wacky.  for whatever reason my `.git/config file` for my local repo was missing the e-mail address.  I updated the config, made a nothing change to the docs and pushed that. Hopefully that will resolve the e-mail address problem.  I'm sorry for the confusion.  

Let me know if this is easier for me to close this PR and resubmit.  This would be the time as we don't have review comments yet.

Thanks!

**Comment by michael-ciniawsky** [comment]
When closing and reopening this PR doesn't resolve the issue, you can also close it entirely and resubmit a 'clean' one :)

**Comment by ecarlisle** [comment]
I'm closing this PR and replacing it with https://github.com/webpack-contrib/source-map-loader/pull/36 .

**Pull request closed without merging**
