### PR TITLE
fix(index): source maps with root-relative paths

### PR DESCRIPTION
**Pull request by iclanton**
`source-map-loader` doesn't correctly handle sourcemaps with root-relative `sourceRoot` properties in sourcemaps.

Consider the following example sourcemap:

```JSON
{
  "version": 3,
  "file": "my-file.js",
  "sourceRoot": "/code/my-project/src/",
  "sources": [
    "my-file.ts"
  ],
  "names": [],
  "mappings": "AAAA, ..."
}
```

`source-map-loader` will resolve each of the files referenced in `sources` to be under `sourceRoot` [here](https://github.com/webpack-contrib/source-map-loader/blob/master/index.js#L67-L68) (so in this example, the path becomes `/code/my-project/src//my-file.ts`), and then it will attempt to resolve each of the paths it constructed using `loaderUtils.urlToRequest`. As per the [documentation of `urlToRequest`](https://github.com/webpack/loader-utils#urltorequest), the `root` argument is required for paths that are root-relative. Root-relative paths work correctly on Windows because of [this condition](https://github.com/webpack/loader-utils/blob/master/lib/urlToRequest.js#L15-L17), but on UNIX and UNIX-like operating systems, without the `root` argument, [this condition](https://github.com/webpack/loader-utils/blob/master/lib/urlToRequest.js#L44-L46) applies. This means, the path in our example above is turned into `.//code/my-project/src//my-file.ts`, which isn't a valid path.

This issue is easily fixed by passing `true` to the `root` parameter of `urlToRequest`, which causes paths with a leading `/` to be passed through ([this condition](https://github.com/webpack/loader-utils/blob/master/lib/urlToRequest.js#L30-L34)).

### CODE REVIEW

**Comment by zuohaocheng** [comment]
Looks good. May you add a test case?

**Comment by iclanton** [comment]
Excellent! Can this get merged in? How frequently do you guys release this package?

**Comment by zuohaocheng** [comment]
@d3viant0ne Could you help to merge it?

**Comment by iclanton** [comment]
@d3viant0ne can you take a look at this?

**Comment by michael-ciniawsky** [comment]
Released in [`v0.2.4`](https://github.com/webpack-contrib/source-map-loader/releases/tag/v0.2.4) 🎉

**Comment by iclanton** [comment]
Thanks!

**Pull request merged**
