### PR TITLE
Prevent sourcemaps provided by other libs/deps being overwritten

### PR DESCRIPTION
**Pull request by arielschiavoni**
Lets say we have a dependency `echo` that have been compiled from ES6 to ES5 and provide us
its sourcemaps files. We want to be able to bundle it together with its sourcemaps, so we can debug not just our code but the libraries that provide us their sourcemaps.

Because sourcemaps are generated with relative urls like this

```js
 "sources": [
    "../index.js"
  ]
```
  
when a webpack bundle is generated, webpack will take the sourceMaps that `source-map-loader` emits and they will be overwritten if the source files between the different libraries are named the same way.

To avoid this problem it is necessary to process the sourceMaps's `sources` and give them the context of the library that is being processed.

Similar PR https://github.com/webpack-contrib/source-map-loader/pull/26

### CODE REVIEW

**Comment by arielschiavoni** [comment]
Hi @hipstersmoothie I downgraded the syntax to ES5 but it seems that the reason why the build fails is related to `yarn` not supporting `node 4.3` anymore.

Should I change `.travis.yml` node version from `4.3` to `4.8` (minimum version supported by `yarn`)?

travis_failed_node_v4_3

travis_yarn_error

**Comment by hipstersmoothie** [comment]
@arielschiavoni It looks like the last commit merged to master updates that file. Wanna rebase?

**Comment by hipstersmoothie** [comment]
Sweet! @d3viant0ne @michael-ciniawsky 🙌

**Comment by d3viant0ne** [comment]
A word on current master, the latest minor version of `source-map` from mozilla drops support for Node < 8 ( yeah, I know that makes no sense at all ).

So, two options. This goes to master & it's node 8 only OR I will branch off the latest tag and we can run two version ranges.

Sorry about the dependency thing, I argued against it as a minor version & was quickly dismissed with `0.whatever` isn't stable, blah blah.

**Comment by hipstersmoothie** [comment]
I think it's fine if its only node 8. Managing 2 version ranges might get tricky

**Comment by niksy** [comment]
Is this still active? What can we do to get this merged?

**Comment by hipstersmoothie** [comment]
@hipstersmoothie i've hit this issue again in a completely different project. Would you merge + release a PR if i factored out the necessary parts?

**Comment by pesimeao** [comment]
This is great @arielschiavoni ! Really important for mono-repos or if you are using a linked package by `npm link` for libraries. Thanks!

**Comment by evilebottnawi** [comment]
Fixed in the master

**Pull request closed without merging**
