### PR TITLE
refactor: prevent source maps overwrites

### PR DESCRIPTION
**Pull request by arielschiavoni**
This PR includes the following changes
- Setup ES6, add eslint and refactor tests
- Add travis CI config
- Update npm dependencies
- Prevent sourcemaps overwrite
### Prevent sourcemaps overwrite

Lets say we have two libs (`hi` and `echo`) that have been compiled from ES6 to ES5 and provide us their sourcemaps files. We want to be able to bundle them and load their sourcemaps, so we can debug not  just our code but the libraries that provide us their sourcemaps.
Because sourcemaps are generated with relative urls like this

``` js
     "sources": [
        "../index.js"
      ]
```

when a webpack bundle is generated, webpack will take the sourceMaps that `source-map-loader` emits
and they will be overwritten if the source files between the different libraries are named the same way.

To avoid this problem it is necessary to process the sourceMaps's `sources` and give them the `context`
of the library that is being processed.

### CODE REVIEW

**Comment by developit** [comment]
+1

**Comment by jsg2021** [comment]
I would love to see this or #9 merged :+1:

**Comment by developit** [comment]
Might be worth separating the overwrite logic from the ES6 refactor so @sokra can merge easily?

**Comment by zerkalica** [comment]
Project is dead? Is better solution/fork?

**Comment by michael-ciniawsky** [comment]
@arielschiavoni First, sry for the insanely late response :), are you still interested in this? If so please sign the CLA by closing and reopening the PR ro trigger the CLA Bot again and rebase against current master.

**Comment by arielschiavoni** [comment]
Hi @michael-ciniawsky no problem, in the next days I'll check what I did because I honestly don't remember :-) and I'll update the PR according to your previous comments.

**Comment by andreineculau** [comment]
fwiw this is an insane request after **2 years** for an important bugfix (even with the bulk refactoring, eslint, travis, etc)

**Comment by jsg2021** [comment]
I think #26 covers this

**Comment by hipstersmoothie** [comment]
Just wasted a day realizing the path for two source maps were the same and overwriting each other :(. Any chance of this ever getting merged? And if not I think it should be split into two PRs. One with the upgrades and one with the bug fix.

**Comment by arielschiavoni** [comment]
I am going to close this PR and send a new one only with the bug fix.

**Comment by arielschiavoni** [comment]
Here is the new PR without the whole refactor https://github.com/webpack-contrib/source-map-loader/pull/63

**Pull request closed without merging**
