### PR TITLE
Add support for 'quiet' option to disable warning output.

### PR DESCRIPTION
**Pull request by swernerx**
Warnings from source map loader are correct, but they are typically not fixable by the author of the current application as it's most likely a 3rd party package which is reported.

This PR contains / is in sync with https://github.com/webpack-contrib/source-map-loader/pull/26

It uses the basic option infrastructure from this pull request and just adds another option `quiet` to use an empty placeholder function instead of `this.emitWarning`. 

I also added an additional test for checking the new behavior with the option enabled.

As this PR does not affect the default behavior it should be okay as part of a minor release.

### CODE REVIEW

**Comment by sokra** [comment]
You can use `stats.filterWarnings` to hide specific warnings in webpack.

**Comment by evilebottnawi** [comment]
Sorry for delay, and thanks for the PR, but we don't need this option because webpack has `stats.warningsFilter` for filtering warnings + absolute paths fixed in master. Anyway feel free to feedback and feel free to open a new issue if you found warnings very annoying in some cases (+ feedback why). 

Also I update docs and add example for ignoring warnings.

**Comment by vdh** [comment]
@evilebottnawi @sokra The `stats.warningsFilter` workaround is not ideal, hiding warnings doesn't remove them entirely, because Webpack (specifically, `webpack-dev-middleware`) will still consider the compile to be compromised:
```
ℹ ｢wdm｣: Compiled with warnings.
```

**Comment by evilebottnawi** [comment]
@vdh we need to solve this https://github.com/webpack/webpack/issues/7841

**Comment by vdh** [comment]
@evilebottnawi Is there a reason why this isn't just something that should be addressed inside `source-map-loader`? Prevention is worth a pound of cure, after all. Preventing warnings seems like it would be more straightforward than trying to silence them after they're already been emitted and tripping up the rest of Webpack…?

**Comment by evilebottnawi** [comment]
@vdh because in this case every loader should have the `warningsFilter` option, and in the future developers tell us that we made everything uncomfortable, so you have one place for filtering warnings

**Pull request closed without merging**
